// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {uci} from '../models';
import {registry} from '../models';

export function AddCustomEngine(arg1:string,arg2:string):Promise<registry.InstalledEngine>;

export function ApplyEngineProfile(arg1:string,arg2:string):Promise<Record<string, string>>;

export function ListEngineProfiles(arg1:string):Promise<Array<main.EngineProfile>>;

export function GetCPUFeatures():Promise<string>;

export function GetEngineOptionConfig(arg1:string):Promise<main.EngineOptionConfig>;

export function GetEngineOptions(arg1:string):Promise<Record<string, uci.UCIOption>>;

export function GetGameDetail(arg1:string,arg2:number):Promise<main.GameDetail>;

export function GetTournament(arg1:string):Promise<main.TournamentSummary>;

export function GetTournamentPGN(arg1:string):Promise<string>;

export function InstallEngine(arg1:string):Promise<void>;

export function ListAvailableEngines():Promise<Array<registry.EngineInfo>>;

export function PickEngineBinary():Promise<string>;

export function ListEngines():Promise<Array<uci.EngineInfo>>;

export function ListInstalledEngines():Promise<Array<registry.InstalledEngine>>;

export function ListTournaments():Promise<Array<main.TournamentSummary>>;

export function RegisterEngine(arg1:string,arg2:string):Promise<void>;

export function SetAnalysisThrottle(arg1:number):Promise<void>;

export function SetEngineOption(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetEngineOptionConfig(arg1:string,arg2:Record<string, string>):Promise<void>;

export function StartAnalysis(arg1:main.AnalysisParams):Promise<void>;

export function StartEngine(arg1:string):Promise<void>;

export function StartTournament(arg1:main.TournamentSpec):Promise<string>;

export function StopAnalysis(arg1:Array<string>):Promise<void>;

export function StopEngine(arg1:string):Promise<void>;

export function StopTournament(arg1:string):Promise<void>;

export function UninstallEngine(arg1:string):Promise<void>;

export function UnregisterEngine(arg1:string):Promise<void>;
