// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUFeatures() {
  return window['go']['main']['App']['GetCPUFeatures']();
}

export function GetEngineOptionConfig(arg1) {
  return window['go']['main']['App']['GetEngineOptionConfig'](arg1);
}

export function GetEngineOptions(arg1) {
  return window['go']['main']['App']['GetEngineOptions'](arg1);
}

export function GetGameDetail(arg1, arg2) {
  return window['go']['main']['App']['GetGameDetail'](arg1, arg2);
}

export function GetTournament(arg1) {
  return window['go']['main']['App']['GetTournament'](arg1);
}

export function InstallEngine(arg1) {
  return window['go']['main']['App']['InstallEngine'](arg1);
}

export function ListAvailableEngines() {
  return window['go']['main']['App']['ListAvailableEngines']();
}

export function ListEngines() {
  return window['go']['main']['App']['ListEngines']();
}

export function ListInstalledEngines() {
  return window['go']['main']['App']['ListInstalledEngines']();
}

export function ListTournaments() {
  return window['go']['main']['App']['ListTournaments']();
}

export function RegisterEngine(arg1, arg2) {
  return window['go']['main']['App']['RegisterEngine'](arg1, arg2);
}

export function SetAnalysisThrottle(arg1) {
  return window['go']['main']['App']['SetAnalysisThrottle'](arg1);
}

export function SetEngineOption(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEngineOption'](arg1, arg2, arg3);
}

export function SetEngineOptionConfig(arg1, arg2) {
  return window['go']['main']['App']['SetEngineOptionConfig'](arg1, arg2);
}

export function StartAnalysis(arg1) {
  return window['go']['main']['App']['StartAnalysis'](arg1);
}

export function StartEngine(arg1) {
  return window['go']['main']['App']['StartEngine'](arg1);
}

export function StartTournament(arg1) {
  return window['go']['main']['App']['StartTournament'](arg1);
}

export function StopAnalysis(arg1) {
  return window['go']['main']['App']['StopAnalysis'](arg1);
}

export function StopEngine(arg1) {
  return window['go']['main']['App']['StopEngine'](arg1);
}

export function StopTournament(arg1) {
  return window['go']['main']['App']['StopTournament'](arg1);
}

export function UninstallEngine(arg1) {
  return window['go']['main']['App']['UninstallEngine'](arg1);
}

export function UnregisterEngine(arg1) {
  return window['go']['main']['App']['UnregisterEngine'](arg1);
}
