// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEngineOptions(arg1) {
  return window['go']['main']['App']['GetEngineOptions'](arg1);
}

export function ListEngines() {
  return window['go']['main']['App']['ListEngines']();
}

export function RegisterEngine(arg1, arg2) {
  return window['go']['main']['App']['RegisterEngine'](arg1, arg2);
}

export function SetAnalysisThrottle(arg1) {
  return window['go']['main']['App']['SetAnalysisThrottle'](arg1);
}

export function SetEngineOption(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEngineOption'](arg1, arg2, arg3);
}

export function StartAnalysis(arg1) {
  return window['go']['main']['App']['StartAnalysis'](arg1);
}

export function StartEngine(arg1) {
  return window['go']['main']['App']['StartEngine'](arg1);
}

export function StopAnalysis(arg1) {
  return window['go']['main']['App']['StopAnalysis'](arg1);
}

export function StopEngine(arg1) {
  return window['go']['main']['App']['StopEngine'](arg1);
}

export function UnregisterEngine(arg1) {
  return window['go']['main']['App']['UnregisterEngine'](arg1);
}
