// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uci} from '../models';
import {main} from '../models';

export function GetEngineOptions(arg1:string):Promise<Record<string, uci.UCIOption>>;

export function ListEngines():Promise<Array<uci.EngineInfo>>;

export function RegisterEngine(arg1:string,arg2:string):Promise<void>;

export function SetAnalysisThrottle(arg1:number):Promise<void>;

export function SetEngineOption(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartAnalysis(arg1:main.AnalysisParams):Promise<void>;

export function StartEngine(arg1:string):Promise<void>;

export function StopAnalysis(arg1:Array<string>):Promise<void>;

export function StopEngine(arg1:string):Promise<void>;

export function UnregisterEngine(arg1:string):Promise<void>;
